# Generated by Django 2.0.3 on 2019-05-24 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='songs',
            name='new',
            field=models.TextField(null=True),
        ),
    ]
